# Generated by Django 5.0.3 on 2024-04-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0007_compra_data_alter_compra_status_alter_compra_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='tipo_pagamento',
            field=models.IntegerField(choices=[(1, 'Cartão de Crédito'), (2, 'Cartão de Débito'), (3, 'PIX'), (4, 'Boleto'), (5, 'Transferência Bancária'), (6, 'Dinheiro'), (7, 'Outro')], default=1),
        ),
        migrations.AlterField(
            model_name='compra',
            name='status',
            field=models.IntegerField(choices=[(1, 'Carrinho'), (2, 'Realizado'), (3, 'Pago'), (4, 'Entregue')], default=1),
        ),
    ]
